# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "dk-state-bucket"
    encrypt = true
    key     = "ecs-gateway/terraform.tfstate"
    profile = "leedonggyu"
    region  = "ap-northeast-2"
  }
}
